CREATE TABLE Users (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    Email TEXT NOT NULL,
    Password TEXT NOT NULL
);

CREATE TABLE WasteGroups (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    Description TEXT
);

CREATE TABLE WasteItems (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    GroupID INTEGER NOT NULL,
    Description TEXT,
    FOREIGN KEY (GroupID) REFERENCES WasteGroups(ID)
);

CREATE TABLE DisposalReports (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    UserID INTEGER NOT NULL,
    ItemID INTEGER NOT NULL,
    DateTime TEXT NOT NULL,
    Quantity INTEGER NOT NULL,
    Remarks TEXT,
    FOREIGN KEY (UserID) REFERENCES Users(ID),
    FOREIGN KEY (ItemID) REFERENCES WasteItems(ID)
);
